# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Minecraft Properties
minecraft_version = 1.21.1
minecraft_version_supported = [1.21,1.21.1]
minecraft_version_filter = releases
minecraft_version_lower = 1.20.6
minecraft_version_upper = 1.21.4

# File Name
minecraft_version_name = 1.21(.1)
archives_base_name = MoreVariantsCore

# Mod Properties
mod_id = more_variants_core
mod_name = More Variants Core
mod_name_short = More Variants Core
mod_description = Core mod for 'More Variants' Add-ons
mod_version = 0.9.7
mod_license = CC-BY-NC-SA-4.0
maven_group = de.pnku

# Dependencies
    # More Variants: Add-ons
        # Pale Oak Backport
        m_v_pale_oak_backport_version_id = 0.9.8
            # Pale Oak
            vanillabackport_version_id = d0eHO236
            platform_version_id = BbIdNbF1
    # Config (e.g. mShieldV) [-'+fabric']
    cloth_config_version = 15.0.140
    modmenu_version = 11.0.4
    # Every Compat [!]
    every_compat_version=1.21-2.11.38
    moonlight_version=1.21-2.29.33
        # Testing via Wilder Wild [*]
        wilder_wild_version=4.2.1-mc1.21.1
        frozenlib_version=2.2.4-mc1.21.1
    # More X Variants
        # Quad
        quad_version_id = 5SqDjW5O
        # Main Variants
        m_barrel_v_version_id = XMlrbush
        m_bed_v_version_id = oIMNCccX
        m_beehive_v_version_id = HX8sTWXJ
        m_bookshelf_v_lol_version_id = hgLqbkLp
        m_cartography_t_version_id = prFJW9dO
        m_chiseled_bookshelf_v_version_id = TEjDc4FZ
        m_chest_v_lol_version_id = EiHVohhQ
        m_composter_v_version_id = 1GpHH6JW
            m_feeding_trough_v_version_id = uHZDgZ2J
                animal__feeding__trough_version_id = BgW2cRLu
                    # Archtictury API [-'+fabric']
                    architectury_api_version = 13.0.8
        m_crafter_v_version_id = JUFzIifZ
        m_crafting_t_lol_version_id = F1NJF7Dr
        m_fletching_t_version_id = QdvINYhR
        m_furnace_v_lol_version_id = Ks6oEPuf
        m_grindstone_v_version_id = ZMwlg7ed
        m_jukebox_noteblock_v_version_id = 3oRGOnhg
        m_lectern_v_version_id = WFrSmY89
        m_loom_v_version_id = OUr45Ww1
        m_nemos_woodcutter_v_version_id = 8gaKzdzx
            nemos_woodcutter_version_id = XDslDeud
        m_shield_v_version_id = R9OEUoPu
        m_smithing_t_version_id = io53NuUI
        m_smoker_v_version_id = QG5iRqXf
        # MStV
            mstv_version = 1.4.17
            mstv_version_id = gHf92NDy
            # MStV+
                mstv_m_armor_stand_v_version_id = 41bIMpBZ
                mstv_m_frame_v_version_id = 2NgCa7qS
                    fast_item_frames_version_id = drSo3Q2h
                    puzzles_lib_version_id = L007zH3l
                    forge_config_api_port_version_id = N5qzq0XV
                mstv_nemos_m_ladder_v_version_id = YQ3JN1lp
                mstv_m_rail_v_version_id = FOKpTt0j
                mstv_m_fishing_rod_v_version_id = hfXZu934
                mstv_m_tool_v_version_id = Pf6vfeXp
                mstv_m_torch_v_version_id = dm3Cksrk
                mstv_m_weapon_v_version_id = qKgQmLzE
