# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Minecraft Properties
minecraft_version = 1.20.1
minecraft_version_supported = [1.20.1]
minecraft_version_filter = releases
minecraft_version_lower = 1.19.4
minecraft_version_upper = 1.20.5

# File Name
minecraft_version_name = 1.20.1
archives_base_name = MoreVariantsCore

# Mod Properties
mod_id = more_variants_core
mod_name = More Variants Core
mod_name_short = More Variants Core
mod_description = Core mod for 'More Variants' Add-ons
mod_version = 1.0.0
mod_license = CC-BY-NC-SA-4.0
maven_group = de.pnku

# Dependencies
    # More Variants: Add-ons
        # Pale Oak Backport
        m_v_pale_oak_backport_version = 1.0.0
        m_v_pale_oak_backport_version_id =
            # Pale Oak
            vanillabackport_version_id = OQDowJW0
            platform_version_id = bzUnKsaY
    # Config (e.g. mShieldV) [-'+fabric']
    cloth_config_version = 11.1.136
    modmenu_version = 7.2.2
    # Every Compat [!]
    every_compat_version=1.20-2.9.20
    moonlight_version=1.20-2.16.32
        # Testing via Wilder Wild [*]
        wilder_wild_version=3.0.7-mc1.20.1
        frozenlib_version=1.9.3-mc1.20.1
    # More X Variants
        # Quad
        quad_version_id = 13NoFEPW
        # Main Variants
        m_barrel_v_version_id = rtcvCTsq
        m_bed_v_version_id = XVjlBItk
        m_beehive_v_version_id = XRWhmjM8
        m_bookshelf_v_lol_version_id = auCccWh0
        m_cartography_t_version_id = QtKq4MRU
        m_chiseled_bookshelf_v_version_id = QocqHcr7
        m_chest_v_lol_version_id = 4RTlXzWr
        m_composter_v_version_id = PvwA9wgj
            m_feeding_trough_v_version_id = vlBCQPHY
                animal__feeding__trough_version_id = WkJeqkhZ
                    # Archtictury API [-'+fabric']
                    architectury_api_version = 9.2.14
        m_crafter_v_version_id = JUFzIifZ
        m_crafting_t_lol_version_id = ALemKQdm
        m_fletching_t_version_id = BvmXPh2x
        m_furnace_v_lol_version_id = YekF8rP5
        m_grindstone_v_version_id = ONh7Rg92
        m_jukebox_noteblock_v_version_id = mem2c8Og
        m_lectern_v_version_id = 7n4KPaNT
        m_loom_v_version_id = 2Kjt5ncs
        m_nemos_woodcutter_v_version_id = i00ky6lW
            nemos_woodcutter_version_id = blsVX40z
        m_shield_v_version_id = rimMHVqc
        m_smithing_t_version_id = BdRdglek
        m_smoker_v_version_id = U5jQhjQU
        # MStV
            mstv_version = 1.4.17
            mstv_version_id = KJCqDjd8
            # MStV+
                mstv_m_armor_stand_v_version_id = vNBYIUlz
                mstv_m_frame_v_version_id = 74uQj6R7
                    fast_item_frames_version_id = 9FkBaot5
                    puzzles_lib_version_id = N8gFdljq
                    forge_config_api_port_version_id = HvR3IdRE
                mstv_nemos_m_ladder_v_version_id = T876C1Pm
                mstv_m_rail_v_version_id = wRxPb57n
                mstv_m_fishing_rod_v_version_id = Wi8tcqH8
                mstv_m_tool_v_version_id = W4mldBey
                mstv_m_torch_v_version_id = MhWJ607E
                mstv_m_weapon_v_version_id = pix16zmI
        # Nemo
        nemos_campfires_version_id = nPbI0QCl
